### ISSUE TITLE
[BUG] Issues with inheritance

### ISSUE THREAD

**Issue by stongef-sonepar** [mark-nicepants/figma2flutter#15]
See bellow

**Comment by frederikstonge** [comment]
Update on the problem :

We have updated our tokens to support multiple theme and it looks like they are split in different categories, color themes, and semantic themes. ITokens generates with only colors and material colors, but nothing related to semantic.

Here is a screenshot with the issue : 
![image](https://github.com/mark-nicepants/figma2flutter/assets/5427239/bb22d618-ba13-4715-9128-708556c58551)

This is the generated files : 
[tokens.g.zip](https://github.com/mark-nicepants/figma2flutter/files/14746356/tokens.g.zip)

And here's the tokens file : 
[tokens.json](https://github.com/mark-nicepants/figma2flutter/files/14746360/tokens.json)

**Comment by frederikstonge** [comment]
@freemansoft I'd like your input on this.

How is ITokens generated? Is it generated with overridden properties in all themes, and ignoring those who are missing in at least 1 theme?

Would there be a way to include missing overridden properties but as nullable?

**Comment by frederikstonge** [comment]
Adding : "semantic": "source", in base theme `selectedTokenSets` seems to include the missing properties, but other issues are raised because some themes are not redefining these properties. A big refactor of how we generate code with inheritance would be required to fix this :(

**Comment by freemansoft** [comment]
Why was this bug marked completed?  The last message says a bunch of work needs to be done.

**Comment by frederikstonge** [comment]
stongef-sonepar is actually my work account. I manage to make it work, my job is using figma studio and are creating partial themes, which is clearly not supported in flutter. I changed the definition of $themes in the tokens file and generation worked.
