### ISSUE TITLE
[FEATURE REQUEST] Push current main to pub.dev as 0.2.1-alpha or 0.3.0-alpha or something

### ISSUE THREAD

**Issue by freemansoft** [mark-nicepants/figma2flutter#18]
### :speech_balloon: Description
Can we push the current main to pub.dev with a new version?  There was a flurry of activity after the October 7 tagging for 0.2.0-alpha

Note that the version number is bumped from 0.2.0-alpha to 0.2.1-alpha.  The changes were additive so that may be correct with the assumption that the 3rd digit for pre-releases is the non-breaking change number.

Cans someone add a link to pub.dev on the repo home page?  The github page has no links to pub.dev or to any release packages.

**Comment by frederikstonge** [comment]
@mark-nicepants I have reviewed and merged a few PR, could you release a 0.3.0-alpha version please? :)

**Comment by mark-nicepants** [comment]
Sure, can you please update the CHANGELOG to reflect the changes that are in this release? Ill make a version when thats added!

**Comment by frederikstonge** [comment]
> Sure, can you please update the CHANGELOG to reflect the changes that are in this release? Ill make a version when thats added!

Pull request is up : #26

**Comment by frederikstonge** [comment]
Ready to release

**Comment by mark-nicepants** [comment]
Just pushed 0.3.0-alpha to pub.dev :-)
