### ISSUE TITLE
[BUG] Negative numbers (`-`) in a size name isn't supported (Low Priority)

### ISSUE THREAD

**Issue by kvenn** [mark-nicepants/figma2flutter#33]
### :information_source: Info

**Version: `v0.3.0-beta`**

### :speech_balloon: Description

If there are two values, one with the name `4` and the other with the name `-4`, the generator will generate them both as 
```dart
EdgeInsets get globalSpacing4 => const EdgeInsets.all(4);
EdgeInsets get globalSpacing4 => const EdgeInsets.all(-4);
```

### Suggestion

Replace the `-` with `neg` or `negative`
```dart
EdgeInsets get globalSpacing4 => const EdgeInsets.all(4);
EdgeInsets get globalSpacingNegative4 => const EdgeInsets.all(-4);
```

### :scroll: tokens file you tried to import

```json
{
  "global": {
    "spacing": {
      "-4": {
        "value": "-4",
        "type": "spacing"
      }
      "4": {
        "value": "4",
        "type": "spacing"
      }
  }
}
```

**Comment by freemansoft** [comment]
https://github.com/mark-nicepants/figma2flutter/pull/38 has been merged
